#!/bin/bash

set -e
if [ ! -x "/usr/bin/mysql" ]
then
  echo "Can't execute /usr/bin/mysql"
  exit 1
fi

if [ -z "$1" ]
then
  echo "Usage $0 socket password"
  exit 1
fi

if [ -z "$2" ] 
then
  echo "Usage $0 socket password"
  exit 1
fi

if [ ! -S "$1" ]
then
  echo "Can't find $1"
#  exit 1
fi

SOCKET=$1
PASSWORD=$2

# Connect to socket with empty password.
mysql -S $SOCKET -u root  <<EOF
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${PASSWORD}');
SET PASSWORD FOR 'root'@'127.0.0.1' = PASSWORD('${PASSWORD}');
SET PASSWORD FOR 'root'@'${HOSTNAME}' = PASSWORD('${PASSWORD}');
SET PASSWORD FOR 'root'@'::1' = PASSWORD('${PASSWORD}');
FLUSH PRIVILEGES;
EOF
